
import React from 'react';
import { WordPack } from './types';

export const WORD_PACKS: WordPack[] = [
  {
    name: 'Unit 1 学科王国',
    icon: '📚',
    character: 'Belle',
    characterPrompt: 'A cute flat face icon of Disney Princess Belle, brown hair with a yellow band, big expressive eyes, Pixar style, white background, minimalist.',
    color: 'bg-amber-100',
    words: [
      { id: 'u1-1', en: 'subject', cn: '学科，科目', category: 'Unit 1 学科王国' },
      { id: 'u1-2', en: 'Chinese', cn: '语文(课)', category: 'Unit 1 学科王国' },
      { id: 'u1-3', en: 'English', cn: '英语(课)', category: 'Unit 1 学科王国' },
      { id: 'u1-4', en: 'Maths', cn: '数学(课)', category: 'Unit 1 学科王国' },
      { id: 'u1-5', en: 'PE', cn: '体育(课)', category: 'Unit 1 学科王国' },
      { id: 'u1-6', en: 'Art', cn: '美术(课)', category: 'Unit 1 学科王国' },
      { id: 'u1-7', en: 'Science', cn: '科学(课)', category: 'Unit 1 学科王国' },
      { id: 'u1-8', en: 'IT', cn: '信息科技(课)', category: 'Unit 1 学科王国' },
      { id: 'u1-9', en: 'Music', cn: '音乐(课)', category: 'Unit 1 学科王国' },
      { id: 'u1-10', en: 'best', cn: '最，最高程度地', category: 'Unit 1 学科王国' },
      { id: 'u1-11', en: 'also', cn: '也', category: 'Unit 1 学科王国' },
      { id: 'u1-12', en: 'mouse', cn: '鼠标；老鼠', category: 'Unit 1 学科王国' },
      { id: 'u1-13', en: 'new', cn: '新的', category: 'Unit 1 学科王国' },
      { id: 'u1-14', en: 'timetable', cn: '课程表', category: 'Unit 1 学科王国' },
      { id: 'u1-15', en: 'number', cn: '数字', category: 'Unit 1 学科王国' },
      { id: 'u1-16', en: 'interesting', cn: '有趣的', category: 'Unit 1 学科王国' },
      { id: 'u1-17', en: 'culture', cn: '文化', category: 'Unit 1 学 Park' },
      { id: 'u1-18', en: 'read', cn: '阅读', category: 'Unit 1 学科王国' },
      { id: 'u1-19', en: 'story', cn: '故事', category: 'Unit 1 学科王国' },
      { id: 'u1-20', en: 'all', cn: '全部，都', category: 'Unit 1 学科王国' },
      { id: 'u1-21', en: 'playground', cn: '操场', category: 'Unit 1 学科王国' },
    ]
  },
  {
    name: 'Unit 2 生活城堡',
    icon: '⏰',
    character: 'Donald Duck',
    characterPrompt: 'A cute flat face icon of Disney Donald Duck, blue hat, white face, yellow beak, Pixar style, white background, minimalist.',
    color: 'bg-blue-100',
    words: [
      { id: 'u2-1', en: 'day', cn: '一天，一日', category: 'Unit 2 生活城堡' },
      { id: 'u2-2', en: 'wash', cn: '洗', category: 'Unit 2 生活城堡' },
      { id: 'u2-3', en: 'face', cn: '脸，面孔', category: 'Unit 2 生活城堡' },
      { id: 'u2-4', en: 'have', cn: '吃，喝', category: 'Unit 2 生活城堡' },
      { id: 'u2-5', en: 'dinner', cn: '晚餐', category: 'Unit 2 生活城堡' },
      { id: 'u2-6', en: 'breakfast', cn: '早餐', category: 'Unit 2 生活城堡' },
      { id: 'u2-7', en: 'lunch', cn: '午餐', category: 'Unit 2 生活城堡' },
      { id: 'u2-8', en: "o'clock", cn: '...点钟', category: 'Unit 2 生活城堡' },
      { id: 'u2-9', en: 'early', cn: '早的', category: 'Unit 2 生活城堡' },
      { id: 'u2-10', en: 'thirty', cn: '三十', category: 'Unit 2 生活城堡' },
      { id: 'u2-11', en: 'first', cn: '首先', category: 'Unit 2 生活城堡' },
      { id: 'u2-12', en: 'twenty', cn: '二十', category: 'Unit 2 生活城堡' },
      { id: 'u2-13', en: 'class', cn: '课，上课', category: 'Unit 2 生活城堡' },
      { id: 'u2-14', en: 'eleven', cn: '十一', category: 'Unit 2 生活城堡' },
      { id: 'u2-15', en: 'sport', cn: '体育运动', category: 'Unit 2 生活城堡' },
      { id: 'u2-16', en: 'fifteen', cn: '十五', category: 'Unit 2 生活城堡' },
      { id: 'u2-17', en: 'bed', cn: '床', category: 'Unit 2 生活城堡' },
    ]
  },
  {
    name: 'Unit 3 星期聚会',
    icon: '🗓️',
    character: 'Daisy Duck',
    characterPrompt: 'A cute flat face icon of Disney Daisy Duck, pink bow, white face, yellow beak, long eyelashes, Pixar style, white background, minimalist.',
    color: 'bg-pink-100',
    words: [
      { id: 'u3-1', en: 'week', cn: '周，星期', category: 'Unit 3 星期聚会' },
      { id: 'u3-2', en: 'Sunday', cn: '星期天', category: 'Unit 3 星期聚会' },
      { id: 'u3-3', en: 'Monday', cn: '星期一', category: 'Unit 3 星期聚会' },
      { id: 'u3-4', en: 'Tuesday', cn: '星期二', category: 'Unit 3 星期聚会' },
      { id: 'u3-5', en: 'Wednesday', cn: '星期三', category: 'Unit 3 星期聚会' },
      { id: 'u3-6', en: 'Thursday', cn: '星期四', category: 'Unit 3 星期聚会' },
      { id: 'u3-7', en: 'Friday', cn: '星期五', category: 'Unit 3 星期聚会' },
      { id: 'u3-8', en: 'Saturday', cn: '星期六', category: 'Unit 3 星期聚会' },
      { id: 'u3-9', en: 'up', cn: '起床', category: 'Unit 3 星期聚会' },
      { id: 'u3-10', en: 'so', cn: '那么', category: 'Unit 3 星期聚会' },
      { id: 'u3-11', en: 'early', cn: '提早', category: 'Unit 3 星期聚会' },
      { id: 'u3-12', en: 'when', cn: '什么时候', category: 'Unit 3 星期聚会' },
      { id: 'u3-13', en: 'every', cn: '每个', category: 'Unit 3 星期聚会' },
      { id: 'u3-14', en: 'at', cn: '在(时间)', category: 'Unit 3 星期聚会' },
      { id: 'u3-15', en: 'today', cn: '今天', category: 'Unit 3 星期聚会' },
      { id: 'u3-16', en: 'cinema', cn: '电影院', category: 'Unit 3 星期聚会' },
      { id: 'u3-17', en: 'dancing', cn: '跳舞', category: 'Unit 3 星期聚会' },
      { id: 'u3-18', en: 'lesson', cn: '一节课', category: 'Unit 3 星期聚会' },
      { id: 'u3-19', en: 'walk', cn: '遛', category: 'Unit 3 星期聚会' },
      { id: 'u3-20', en: 'dog', cn: '狗', category: 'Unit 3 星期聚会' },
      { id: 'u3-21', en: 'tomorrow', cn: '明天', category: 'Unit 3 星期聚会' },
      { id: 'u3-22', en: 'free', cn: '空闲的', category: 'Unit 3 星期聚会' },
    ]
  },
  {
    name: 'Unit 4 运动中心',
    icon: '⚽',
    character: 'Pluto',
    characterPrompt: 'A cute flat face icon of Disney Pluto the dog, orange head, floppy black ears, big smile, Pixar style, white background, minimalist.',
    color: 'bg-orange-100',
    words: [
      { id: 'u4-1', en: 'play', cn: '打球/踢球', category: 'Unit 4 运动中心' },
      { id: 'u4-2', en: 'football', cn: '足球', category: 'Unit 4 运动中心' },
      { id: 'u4-3', en: 'ping-pong', cn: '乒乓球', category: 'Unit 4 运动中心' },
      { id: 'u4-4', en: 'basketball', cn: '篮球', category: 'Unit 4 运动中心' },
      { id: 'u4-5', en: 'great', cn: '非常的', category: 'Unit 4 运动中心' },
      { id: 'u4-6', en: 'well', cn: '好', category: 'Unit 4 运动中心' },
      { id: 'u4-7', en: 'try', cn: '试', category: 'Unit 4 运动中心' },
    ]
  },
  {
    name: 'Unit 5 机器人岛',
    icon: '🤖',
    character: 'Elsa',
    characterPrompt: 'A cute flat face icon of Disney Princess Elsa, light blue hair, silver crown, blue eyes, Pixar style, white background, minimalist.',
    color: 'bg-cyan-100',
    words: [
      { id: 'u5-1', en: 'different', cn: '不同的', category: 'Unit 5 机器人岛' },
      { id: 'u5-2', en: 'same', cn: '相同的', category: 'Unit 5 机器人岛' },
      { id: 'u5-3', en: 'hair', cn: '头发', category: 'Unit 5 机器人岛' },
      { id: 'u5-4', en: 'eye', cn: '眼睛', category: 'Unit 5 机器人岛' },
      { id: 'u5-5', en: 'ear', cn: '耳朵', category: 'Unit 5 机器人岛' },
      { id: 'u5-6', en: 'nose', cn: '鼻子', category: 'Unit 5 机器人岛' },
      { id: 'u5-7', en: 'mouth', cn: '嘴', category: 'Unit 5 机器人岛' },
      { id: 'u5-8', en: 'arm', cn: '手臂', category: 'Unit 5 机器人岛' },
      { id: 'u5-9', en: 'leg', cn: '腿', category: 'Unit 5 机器人岛' },
      { id: 'u5-10', en: 'robot', cn: '机器人', category: 'Unit 5 机器人岛' },
      { id: 'u5-11', en: 'his', cn: '他的', category: 'Unit 5 机器人岛' },
      { id: 'u5-12', en: 'tall', cn: '高的', category: 'Unit 5 机器人岛' },
      { id: 'u5-13', en: 'doll', cn: '玩具娃娃', category: 'Unit 5 机器人岛' },
      { id: 'u5-14', en: 'her', cn: '她的', category: 'Unit 5 机器人岛' },
      { id: 'u5-15', en: 'small', cn: '小的', category: 'Unit 5 机器人岛' },
      { id: 'u5-16', en: 'bring', cn: '带来', category: 'Unit 5 机器人岛' },
      { id: 'u5-17', en: 'lots of', cn: '大量', category: 'Unit 5 机器人岛' },
      { id: 'u5-18', en: 'puppet', cn: '玩偶', category: 'Unit 5 机器人岛' },
      { id: 'u5-19', en: 'show', cn: '表演', category: 'Unit 5 机器人岛' },
    ]
  },
  {
    name: 'Unit 6 天气预报',
    icon: '☁️',
    character: 'Snow White',
    characterPrompt: 'A cute flat face icon of Disney Snow White, short black hair, red bow headband, Pixar style, white background, minimalist.',
    color: 'bg-red-50',
    words: [
      { id: 'u6-1', en: 'weather', cn: '天气', category: 'Unit 6 天气预报' },
      { id: 'u6-2', en: 'cloudy', cn: '多云的', category: 'Unit 6 天气预报' },
      { id: 'u6-3', en: 'sunny', cn: '晴朗的', category: 'Unit 6 天气预报' },
      { id: 'u6-4', en: 'cool', cn: '凉爽的', category: 'Unit 6 天气预报' },
      { id: 'u6-5', en: 'rainy', cn: '多雨的', category: 'Unit 6 天气预报' },
      { id: 'u6-6', en: 'hot', cn: '热的', category: 'Unit 6 天气预报' },
      { id: 'u6-7', en: 'windy', cn: '风大的', category: 'Unit 6 天气预报' },
      { id: 'u6-8', en: 'warm', cn: '温暖的', category: 'Unit 6 天气预报' },
      { id: 'u6-9', en: 'money', cn: '钱', category: 'Unit 6 天气预报' },
      { id: 'u6-10', en: 'park', cn: '公园', category: 'Unit 6 天气预报' },
      { id: 'u6-11', en: 'meet', cn: '集合', category: 'Unit 6 天气预报' },
      { id: 'u6-12', en: 'fly a kite', cn: '放风筝', category: 'Unit 6 天气预报' },
      { id: 'u6-13', en: 'worry', cn: '担心', category: 'Unit 6 天气预报' },
      { id: 'u6-14', en: 'umbrella', cn: '雨伞', category: 'Unit 6 天气预报' },
      { id: 'u6-15', en: 'there', cn: '在那里', category: 'Unit 6 天气预报' },
      { id: 'u6-16', en: 'save for a rainy day', cn: '未雨绸缪', category: 'Unit 6 天气预报' },
    ]
  },
  {
    name: 'Unit 7 四季森林',
    icon: '🌳',
    character: 'Cinderella',
    characterPrompt: 'A cute flat face icon of Disney Cinderella, blonde hair, blue headband, blue eyes, Pixar style, white background, minimalist.',
    color: 'bg-blue-50',
    words: [
      { id: 'u7-1', en: 'season', cn: '季节', category: 'Unit 7 四季森林' },
      { id: 'u7-2', en: 'spring', cn: '春天', category: 'Unit 7 四季森林' },
      { id: 'u7-3', en: 'go boating', cn: '去划船', category: 'Unit 7 四季森林' },
      { id: 'u7-4', en: 'winter', cn: '冬天', category: 'Unit 7 四季森林' },
      { id: 'u7-5', en: 'go skating', cn: '去溜冰', category: 'Unit 7 四季森林' },
      { id: 'u7-6', en: 'summer', cn: '夏天', category: 'Unit 7 四季森林' },
      { id: 'u7-7', en: 'ice cream', cn: '冰淇淋', category: 'Unit 7 四季森林' },
      { id: 'u7-8', en: 'go swimming', cn: '去游泳', category: 'Unit 7 四季森林' },
      { id: 'u7-9', en: 'autumn', cn: '秋天', category: 'Unit 7 四季森林' },
      { id: 'u7-10', en: 'go climbing', cn: '去爬山', category: 'Unit 7 四季森林' },
      { id: 'u7-11', en: 'cold', cn: '寒冷的', category: 'Unit 7 四季森林' },
      { id: 'u7-12', en: 'bird', cn: '鸟', category: 'Unit 7 四季森林' },
      { id: 'u7-13', en: 'back', cn: '回原处', category: 'Unit 7 四季森林' },
      { id: 'u7-14', en: 'in', cn: '在时间内', category: 'Unit 7 四季森林' },
      { id: 'u7-15', en: 'year', cn: '年', category: 'Unit 7 四季森林' },
      { id: 'u7-16', en: 'plant', cn: '栽种', category: 'Unit 7 四季森林' },
      { id: 'u7-17', en: 'pick', cn: '采摘', category: 'Unit 7 四季森林' },
      { id: 'u7-18', en: 'snow', cn: '雪', category: 'Unit 7 四季森林' },
    ]
  },
  {
    name: 'Unit 8 假日衣橱',
    icon: '👗',
    character: 'Minnie Mouse',
    characterPrompt: 'A cute flat face icon of Disney Minnie Mouse, big red bow with white dots, black ears, Pixar style, white background, minimalist.',
    color: 'bg-rose-100',
    words: [
      { id: 'u8-1', en: 'holiday', cn: '假期', category: 'Unit 8 假日衣橱' },
      { id: 'u8-2', en: 'clothes', cn: '衣服', category: 'Unit 8 假日衣橱' },
      { id: 'u8-3', en: 'cap', cn: '便帽', category: 'Unit 8 假日衣橱' },
      { id: 'u8-4', en: 'coat', cn: '外套', category: 'Unit 8 假日衣橱' },
      { id: 'u8-5', en: 'skirt', cn: '半身裙', category: 'Unit 8 假日衣橱' },
      { id: 'u8-6', en: 'trousers', cn: '裤子', category: 'Unit 8 假日衣橱' },
      { id: 'u8-7', en: 'dress', cn: '连衣裙', category: 'Unit 8 假日衣橱' },
      { id: 'u8-8', en: 'shirt', cn: '衬衫', category: 'Unit 8 假日衣橱' },
      { id: 'u8-9', en: 'whose', cn: '谁的', category: 'Unit 8 假日衣橱' },
      { id: 'u8-10', en: 'look', cn: '看来好像', category: 'Unit 8 假日衣橱' },
      { id: 'u8-11', en: 'in', cn: '穿着', category: 'Unit 8 假日衣橱' },
      { id: 'u8-12', en: 'sunglasses', cn: '太阳镜', category: 'Unit 8 假日衣橱' },
      { id: 'u8-13', en: 'why', cn: '为什么', category: 'Unit 8 假日衣橱' },
      { id: 'u8-14', en: 'wear', cn: '穿戴', category: 'Unit 8 假日衣橱' },
      { id: 'u8-15', en: 'because', cn: '因为', category: 'Unit 8 假日衣橱' },
      { id: 'u8-16', en: 'bright', cn: '明亮的', category: 'Unit 8 假日衣橱' },
    ]
  }
];
